server:
  port: @server.port@
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
flyway:
  schemas: mst
retry-policy:
  maxAttempts: 10
identity:
  polling:
    url: http://wapi:8022/v1/eventsink/identity
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
wallet:
  polling:
    url: http://wapi:8022/v1/eventsink/wallet
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
withdrawal:
  polling:
    url: http://wapi:8022/v1/eventsink/withdrawal
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    lastEventId: 4780

